BEGIN TRANSACTION;

todo: create resource_room_endpoint_recording_folder_ids
todo: move room_endpoint_recording_folder_ids to resource_room_endpoint_recording_folder_ids
todo: drop room_endpoint_recording_folder_ids

COMMIT TRANSACTION;