/**
 * 2014-05-22: Change maximum length for string columns.
 */
DROP VIEW IF EXISTS specification_summary;
DROP VIEW IF EXISTS alias_specification_summary;
DROP VIEW IF EXISTS reservation_request_summary;
DROP VIEW IF EXISTS reservation_request_state;
DROP VIEW IF EXISTS reservation_request_set_earliest_child;
DROP VIEW IF EXISTS reservation_request_active_usage;
DROP VIEW IF EXISTS reservation_request_earliest_usage;
DROP VIEW IF EXISTS reservation_summary;
DROP VIEW IF EXISTS executable_summary;
DROP VIEW IF EXISTS room_endpoint_earliest_usage;
ALTER TABLE abstract_reservation_request ALTER COLUMN state TYPE VARCHAR(64);
ALTER TABLE abstract_reservation_request ALTER COLUMN reusement TYPE VARCHAR(64);
ALTER TABLE abstract_reservation_request ALTER COLUMN purpose TYPE VARCHAR(64);
ALTER TABLE abstract_reservation_request ALTER COLUMN created_by TYPE VARCHAR(32);
ALTER TABLE abstract_reservation_request ALTER COLUMN updated_by TYPE VARCHAR(32);
ALTER TABLE acl_entry ALTER COLUMN role TYPE VARCHAR(64);
ALTER TABLE acl_entry_dependency ALTER COLUMN type TYPE VARCHAR(64);
ALTER TABLE acl_identity ALTER COLUMN type TYPE VARCHAR(64);
ALTER TABLE acl_identity ALTER COLUMN principal_id TYPE VARCHAR(32);
ALTER TABLE acl_object_class ALTER COLUMN class TYPE VARCHAR(64);
ALTER TABLE alias ALTER COLUMN type TYPE VARCHAR(64);
ALTER TABLE alias_specification_alias_technologies ALTER COLUMN alias_technologies TYPE VARCHAR(64);
ALTER TABLE alias_specification_alias_types ALTER COLUMN alias_types TYPE VARCHAR(64);
ALTER TABLE allocation ALTER COLUMN state TYPE VARCHAR(64);
ALTER TABLE compartment_specification ALTER COLUMN call_initiation TYPE VARCHAR(64);
ALTER TABLE date_time_slot ALTER COLUMN duration TYPE VARCHAR(64);
ALTER TABLE date_time_specification ALTER COLUMN type TYPE VARCHAR(64);
ALTER TABLE date_time_specification ALTER COLUMN relative_date_time TYPE VARCHAR(64);
ALTER TABLE device_resource ALTER COLUMN preferred_technology TYPE VARCHAR(64);
ALTER TABLE device_resource_technologies ALTER COLUMN technologies TYPE VARCHAR(64);
ALTER TABLE endpoint_participant ALTER COLUMN call_initiation TYPE VARCHAR(64);
ALTER TABLE endpoint_participant_technologies ALTER COLUMN technologies TYPE VARCHAR(64);
ALTER TABLE executable ALTER COLUMN state TYPE VARCHAR(64);
ALTER TABLE executable_service ALTER COLUMN state TYPE VARCHAR(64);
ALTER TABLE external_endpoint_set_participant_technologies ALTER COLUMN technologies TYPE VARCHAR(64);
ALTER TABLE external_endpoint_set_technologies ALTER COLUMN technologies TYPE VARCHAR(64);
ALTER TABLE external_endpoint_technologies ALTER COLUMN technologies TYPE VARCHAR(64);
ALTER TABLE invited_person_participant ALTER COLUMN invitation_state TYPE VARCHAR(64);
ALTER TABLE jade_report ALTER COLUMN code TYPE VARCHAR(64);
ALTER TABLE jade_report ALTER COLUMN receiver_agent TYPE VARCHAR(64);
ALTER TABLE jade_report ALTER COLUMN sender_agent TYPE VARCHAR(64);
ALTER TABLE periodic_date_time ALTER COLUMN time_zone TYPE VARCHAR(32);
ALTER TABLE periodic_date_time ALTER COLUMN period TYPE VARCHAR(64);
ALTER TABLE periodic_date_time ALTER COLUMN ending TYPE VARCHAR(32);
ALTER TABLE periodic_date_time_rule ALTER COLUMN date_time_from TYPE VARCHAR(32);
ALTER TABLE periodic_date_time_rule ALTER COLUMN date_time_to TYPE VARCHAR(32);
ALTER TABLE person ALTER COLUMN user_id TYPE VARCHAR(32);
ALTER TABLE person_participant ALTER COLUMN role TYPE VARCHAR(64);
ALTER TABLE reservation_request ALTER COLUMN allocation_state TYPE VARCHAR(64);
ALTER TABLE resource ALTER COLUMN user_id TYPE VARCHAR(32);
ALTER TABLE room_configuration_technologies ALTER COLUMN technologies TYPE VARCHAR(64);
ALTER TABLE room_provider_capability_required_alias_types ALTER COLUMN required_alias_types TYPE VARCHAR(64);
ALTER TABLE scheduler_report ALTER COLUMN technology TYPE VARCHAR(64);
ALTER TABLE scheduler_report ALTER COLUMN duration TYPE VARCHAR(64);
ALTER TABLE scheduler_report ALTER COLUMN max_duration TYPE VARCHAR(64);
ALTER TABLE scheduler_report_alias_types ALTER COLUMN alias_types TYPE VARCHAR(64);
ALTER TABLE scheduler_report_technologies ALTER COLUMN technologies TYPE VARCHAR(64);
ALTER TABLE specification_technologies ALTER COLUMN technologies TYPE VARCHAR(64);
ALTER TABLE technology_set_technologies ALTER COLUMN technologies TYPE VARCHAR(64);
ALTER TABLE user_settings ALTER COLUMN locale TYPE VARCHAR(16);
ALTER TABLE user_settings ALTER COLUMN home_time_zone TYPE VARCHAR(32);
ALTER TABLE user_settings ALTER COLUMN user_id TYPE VARCHAR(32);
ALTER TABLE user_settings ALTER COLUMN current_time_zone TYPE VARCHAR(32);
ALTER TABLE value_provider ALTER COLUMN type TYPE VARCHAR(64);
;
;
