
package cz.cesnet.shongo.rpctest.soapws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Api", targetNamespace = "http://soapws.rpctest.shongo.cesnet.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Api {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://soapws.rpctest.shongo.cesnet.cz/", className = "cz.cesnet.shongo.rpctest.soapws.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://soapws.rpctest.shongo.cesnet.cz/", className = "cz.cesnet.shongo.rpctest.soapws.service.AddResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @return
     *     returns cz.cesnet.shongo.rpctest.soapws.service.Resource
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResource", targetNamespace = "http://soapws.rpctest.shongo.cesnet.cz/", className = "cz.cesnet.shongo.rpctest.soapws.service.GetResource")
    @ResponseWrapper(localName = "getResourceResponse", targetNamespace = "http://soapws.rpctest.shongo.cesnet.cz/", className = "cz.cesnet.shongo.rpctest.soapws.service.GetResourceResponse")
    public Resource getResource();

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws ApiException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://soapws.rpctest.shongo.cesnet.cz/", className = "cz.cesnet.shongo.rpctest.soapws.service.GetMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://soapws.rpctest.shongo.cesnet.cz/", className = "cz.cesnet.shongo.rpctest.soapws.service.GetMessageResponse")
    public String getMessage()
        throws ApiException_Exception
    ;

    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://soapws.rpctest.shongo.cesnet.cz/", className = "cz.cesnet.shongo.rpctest.soapws.service.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://soapws.rpctest.shongo.cesnet.cz/", className = "cz.cesnet.shongo.rpctest.soapws.service.DivResponse")
    public int div(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
