
package cz.cesnet.shongo.rpctest.soapws.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ApiImplService", targetNamespace = "http://soapws.rpctest.shongo.cesnet.cz/", wsdlLocation = "file:/home/martin/project/cesnet/shongo/sw/rpc-test/soap-ws/target/wsdl/ApiImplService.wsdl")
public class ApiImplService
    extends Service
{

    private final static URL APIIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cz.cesnet.shongo.rpctest.soapws.service.ApiImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cz.cesnet.shongo.rpctest.soapws.service.ApiImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/martin/project/cesnet/shongo/sw/rpc-test/soap-ws/target/wsdl/ApiImplService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/martin/project/cesnet/shongo/sw/rpc-test/soap-ws/target/wsdl/ApiImplService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        APIIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ApiImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiImplService() {
        super(APIIMPLSERVICE_WSDL_LOCATION, new QName("http://soapws.rpctest.shongo.cesnet.cz/", "ApiImplService"));
    }

    /**
     * 
     * @return
     *     returns Api
     */
    @WebEndpoint(name = "ApiImplPort")
    public Api getApiImplPort() {
        return super.getPort(new QName("http://soapws.rpctest.shongo.cesnet.cz/", "ApiImplPort"), Api.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Api
     */
    @WebEndpoint(name = "ApiImplPort")
    public Api getApiImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapws.rpctest.shongo.cesnet.cz/", "ApiImplPort"), Api.class, features);
    }

}
